[project]
name = 'find_to_earn'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'

[[project.requirements]]
contract_id = 'SP2ESPYE74G94D2HD9X470426W1R6C2P22B4Z1Q5.commission-trait'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token'

[[project.requirements]]
contract_id = 'SP3BRXZ9Y7P5YP28PSR8YJT39RT51ZZBSECTCADGR.skullcoin-stxcity'

[contracts.skullcoin-competitive-g2-base]
path = 'contracts/skullcoin-competitive-g2-base.clar'
clarity_version = 2
epoch = 2.5

[contracts.skullcoin-competitive-g2-curiosity-shop]
path = 'contracts/skullcoin-competitive-g2-curiosity-shop.clar'
clarity_version = 2
epoch = 2.5

[contracts.skullcoin-competitive-g2-phase1]
path = 'contracts/skullcoin-competitive-g2-phase1.clar'
clarity_version = 2
epoch = 2.5

[contracts.skullcoin-competitive-g2-phase2]
path = 'contracts/skullcoin-competitive-g2-phase2.clar'
clarity_version = 2
epoch = 2.5

[contracts.skullcoin-competitive-g2-phase3]
path = 'contracts/skullcoin-competitive-g2-phase3.clar'
clarity_version = 2
epoch = 2.5

[contracts.skullcoin-quests]
path = 'contracts/skullcoin-quests.clar'
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
