[project]
name = 'find_to_earn_test'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'

[[project.requirements]]
contract_id = 'ST3T54N6G4HN7GPBCYMSDKP4W00C45X19GNH7C0T6.nft-trait.nft-trait'

[[project.requirements]]
contract_id = 'ST3T54N6G4HN7GPBCYMSDKP4W00C45X19GNH7C0T6.commission-trait.commission'

[[project.requirements]]
contract_id = 'ST3T54N6G4HN7GPBCYMSDKP4W00C45X19GNH7C0T6.sip-010-trait-ft-standard.sip-010-trait'

[contracts.base-test-t1]
path = 'contracts/base-test-t1.clar'
clarity_version = 2
epoch = 2.5

[contracts.phase1-test-t1]
path = 'contracts/phase1-test-t1.clar'
clarity_version = 2
epoch = 2.5

[contracts.phase2-test-t1]
path = 'contracts/phase2-test-t1.clar'
clarity_version = 2
epoch = 2.5

[contracts.phase3-test-t1]
path = 'contracts/phase3-test-t1.clar'
clarity_version = 2
epoch = 2.5

[contracts.phase4-test-t1]
path = 'contracts/phase4-test-t1.clar'
clarity_version = 2
epoch = 2.5

[contracts.phase5-test-t1]
path = 'contracts/phase5-test-t1.clar'
clarity_version = 2
epoch = 2.5

[contracts.phase6-test-t1]
path = 'contracts/phase6-test-t1.clar'
clarity_version = 2
epoch = 2.5

[contracts.token-test-t1]
path = 'contracts/token-test-t1.clar'
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
