[project]
name = 'find_to_earn'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'

[[project.requirements]]
contract_id = 'ST3T54N6G4HN7GPBCYMSDKP4W00C45X19GNH7C0T6.commission-trait'

[[project.requirements]]
contract_id = 'ST3T54N6G4HN7GPBCYMSDKP4W00C45X19GNH7C0T6.sip-010-trait'

[[project.requirements]]
contract_id = 'ST3T54N6G4HN7GPBCYMSDKP4W00C45X19GNH7C0T6.nft-trait'

[[project.requirements]]
contract_id = 'ST1F7QA2MDF17S807EPA36TSS8AMEFY4KA9TVGWXT.sbtc-token'

[contracts.skullcoin-competitive-bb-base]
path = 'contracts/skullcoin-competitive-bb-base.clar'
clarity_version = 2
epoch = 2.5

[contracts.skullcoin-competitive-bb-phase1]
path = 'contracts/skullcoin-competitive-bb-phase1.clar'
clarity_version = 2
epoch = 2.5

[contracts.skullcoin-competitive-bb-phase2]
path = 'contracts/skullcoin-competitive-bb-phase2.clar'
clarity_version = 2
epoch = 2.5

[contracts.skullcoin-competitive-bb-phase3]
path = 'contracts/skullcoin-competitive-bb-phase3.clar'
clarity_version = 2
epoch = 2.5

[contracts.skullcoin-competitive-bb-phase4]
path = 'contracts/skullcoin-competitive-bb-phase4.clar'
clarity_version = 2
epoch = 2.5

[contracts.skullcoin-competitive-bb-curiosity-shop]
path = 'contracts/skullcoin-competitive-bb-curiosity-shop.clar'
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false