[project]
name = 'find_to_earn'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'

[[project.requirements]]
contract_id = 'SP2ESPYE74G94D2HD9X470426W1R6C2P22B4Z1Q5.commission-trait'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'SP3BRXZ9Y7P5YP28PSR8YJT39RT51ZZBSECTCADGR.skullcoin-stxcity'

[[project.requirements]]
contract_id = 'ST3T54N6G4HN7GPBCYMSDKP4W00C45X19GNH7C0T6.skullcoin'

[[project.requirements]]
contract_id = 'ST3T54N6G4HN7GPBCYMSDKP4W00C45X19GNH7C0T6.sip-010-trait'

[contracts.skullcoin-competitive-seed-base]
path = 'contracts/skullcoin-competitive-seed-base.clar'
clarity_version = 2
epoch = 2.5

[contracts.skullcoin-competitive-seed-phase1]
path = 'contracts/skullcoin-competitive-seed-phase1.clar'
clarity_version = 2
epoch = 2.5

[contracts.skullcoin-competitive-seed-phase2]
path = 'contracts/skullcoin-competitive-seed-phase2.clar'
clarity_version = 2
epoch = 2.5

clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
